2020-08-13 11:00:07,137 : INFO : Start of Training
2020-08-13 11:00:07,137 : INFO : Run_id:2020-08-13_110007_856129479
2020-08-13 11:00:07,137 : INFO : Start of Data Load, validation and transformation
2020-08-13 11:00:07,137 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 11:00:07,138 : INFO : End of Archiving Old Rejected Files...
2020-08-13 11:00:07,138 : INFO : Start of Archiving Old Validated Files...
2020-08-13 11:00:07,138 : INFO : End of Archiving Old Validated Files...
2020-08-13 11:00:07,138 : INFO : Start of Archiving Old Processed Files...
2020-08-13 11:00:07,141 : INFO : End of Archiving Old Processed Files...
2020-08-13 11:00:07,141 : INFO : Start of Archiving Old Result Files...
2020-08-13 11:00:07,142 : INFO : End of Archiving Old Result Files...
2020-08-13 11:00:07,142 : INFO : Start of Reading values From Schema...
2020-08-13 11:00:07,142 : INFO : End of Reading values From Schema...
2020-08-13 11:00:07,142 : INFO : Start of Validating Column Length...
2020-08-13 11:00:07,153 : INFO : End of Validating Column Length...
2020-08-13 11:00:07,153 : INFO : Start of Validating Missing Values...
2020-08-13 11:00:07,167 : INFO : End of Validating Missing Values...
2020-08-13 11:00:07,167 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 11:00:07,187 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-13 11:00:07,188 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 11:00:07,188 : INFO : Start of Creating Table...
2020-08-13 11:00:07,188 : INFO : Opened training database successfully
2020-08-13 11:00:07,321 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-13 11:00:07,495 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:07,673 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:07,820 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:07,978 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,111 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,234 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,373 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,610 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,727 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,832 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:08,938 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:09,054 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:09,242 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:09,363 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:09,503 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 11:00:09,505 : INFO : End of Creating Table...
2020-08-13 11:00:09,510 : INFO : Opened training database successfully
2020-08-13 11:00:09,511 : INFO : Start of Inserting Data into Table...
2020-08-13 11:01:38,159 : INFO : End of Inserting Data into Table...
2020-08-13 11:01:38,160 : INFO : Start of Exporting Data into CSV...
2020-08-13 11:01:38,161 : INFO : Opened training database successfully
2020-08-13 11:01:38,171 : INFO : End of Exporting Data into CSV...
2020-08-13 11:01:38,172 : INFO : Start of Moving Processed Files...
2020-08-13 11:01:38,175 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-13 11:01:38,175 : INFO : End of Moving Processed Files...
2020-08-13 11:01:38,175 : INFO : End of Data Load, validation and transformation
2020-08-13 11:01:38,176 : INFO : Start of Preprocessing...
2020-08-13 11:01:38,176 : INFO : Start of reading dataset...
2020-08-13 11:01:38,188 : INFO : End of reading dataset...
2020-08-13 11:01:38,188 : INFO : Start of Droping Columns...
2020-08-13 11:01:38,191 : INFO : End of Droping Columns...
2020-08-13 11:01:38,192 : INFO : Start of replacing invalid values...
2020-08-13 11:01:38,277 : INFO : end of replacing invalid values...
2020-08-13 11:01:38,278 : INFO : Start of encode Categorical Values ...
2020-08-13 11:01:38,303 : INFO : end of encode Categorical Values...
2020-08-13 11:01:38,303 : INFO : Start of feature encoding...
2020-08-13 11:01:38,333 : INFO : End of feature encoding...
2020-08-13 11:01:38,335 : INFO : Start of Droping Columns...
2020-08-13 11:01:38,337 : INFO : End of Droping Columns...
2020-08-13 11:01:38,337 : INFO : Start of finding missing values...
2020-08-13 11:01:38,345 : INFO : End of finding missing values...
2020-08-13 11:01:38,346 : INFO : Start of imputing missing values...
2020-08-13 11:01:38,356 : INFO : End of imputing missing values...
2020-08-13 11:01:38,356 : INFO : Start of feature encoding...
2020-08-13 11:01:38,363 : INFO : End of feature encoding...
2020-08-13 11:01:38,363 : INFO : Start of splitting features and label ...
2020-08-13 11:01:38,364 : ERROR : Exception raised while splitting features and label:"['Approved'] not found in axis"
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"
2020-08-13 11:01:38,370 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 343, in preprocess_trainset
    self.X, self.y = self.split_features_label(data1, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 278, in split_features_label
    raise Exception()
Exception
2020-08-13 11:01:38,371 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 343, in preprocess_trainset
    self.X, self.y = self.split_features_label(data1, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 278, in split_features_label
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 348, in preprocess_trainset
    raise Exception
Exception
