2020-08-13 10:49:36,233 : INFO : Start of Training
2020-08-13 10:49:36,233 : INFO : Run_id:2020-08-13_104936_267254202
2020-08-13 10:49:36,234 : INFO : Start of Data Load, validation and transformation
2020-08-13 10:49:36,234 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 10:49:36,234 : INFO : End of Archiving Old Rejected Files...
2020-08-13 10:49:36,234 : INFO : Start of Archiving Old Validated Files...
2020-08-13 10:49:36,234 : INFO : End of Archiving Old Validated Files...
2020-08-13 10:49:36,235 : INFO : Start of Archiving Old Processed Files...
2020-08-13 10:49:36,237 : INFO : End of Archiving Old Processed Files...
2020-08-13 10:49:36,237 : INFO : Start of Archiving Old Result Files...
2020-08-13 10:49:36,238 : INFO : End of Archiving Old Result Files...
2020-08-13 10:49:36,238 : INFO : Start of Reading values From Schema...
2020-08-13 10:49:36,239 : INFO : End of Reading values From Schema...
2020-08-13 10:49:36,239 : INFO : Start of Validating Column Length...
2020-08-13 10:49:36,254 : INFO : End of Validating Column Length...
2020-08-13 10:49:36,254 : INFO : Start of Validating Missing Values...
2020-08-13 10:49:36,267 : INFO : End of Validating Missing Values...
2020-08-13 10:49:36,268 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 10:49:36,292 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-13 10:49:36,292 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 10:49:36,292 : INFO : Start of Creating Table...
2020-08-13 10:49:36,293 : INFO : Opened training database successfully
2020-08-13 10:49:36,462 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-13 10:49:36,590 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:36,717 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:36,851 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:36,967 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,106 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,221 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,337 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,443 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,570 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,717 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:37,880 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:38,018 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:38,124 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:38,240 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:38,358 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 10:49:38,360 : INFO : End of Creating Table...
2020-08-13 10:49:38,366 : INFO : Opened training database successfully
2020-08-13 10:49:38,367 : INFO : Start of Inserting Data into Table...
2020-08-13 10:51:04,206 : INFO : End of Inserting Data into Table...
2020-08-13 10:51:04,207 : INFO : Start of Exporting Data into CSV...
2020-08-13 10:51:04,214 : INFO : Opened training database successfully
2020-08-13 10:51:04,267 : INFO : End of Exporting Data into CSV...
2020-08-13 10:51:04,268 : INFO : Start of Moving Processed Files...
2020-08-13 10:51:04,272 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-13 10:51:04,272 : INFO : End of Moving Processed Files...
2020-08-13 10:51:04,272 : INFO : End of Data Load, validation and transformation
2020-08-13 10:51:04,272 : INFO : Start of Preprocessing...
2020-08-13 10:51:04,273 : INFO : Start of reading dataset...
2020-08-13 10:51:04,284 : INFO : End of reading dataset...
2020-08-13 10:51:04,284 : INFO : Start of Droping Columns...
2020-08-13 10:51:04,287 : INFO : End of Droping Columns...
2020-08-13 10:51:04,287 : INFO : Start of replacing invalid values...
2020-08-13 10:51:04,344 : INFO : end of replacing invalid values...
2020-08-13 10:51:04,344 : INFO : Start of encode Categorical Values ...
2020-08-13 10:51:04,358 : INFO : end of encode Categorical Values...
2020-08-13 10:51:04,358 : INFO : Start of feature encoding...
2020-08-13 10:51:04,377 : INFO : End of feature encoding...
2020-08-13 10:51:04,379 : INFO : Start of Droping Columns...
2020-08-13 10:51:04,381 : INFO : End of Droping Columns...
2020-08-13 10:51:04,381 : INFO : Start of finding missing values...
2020-08-13 10:51:04,388 : INFO : End of finding missing values...
2020-08-13 10:51:04,388 : INFO : Start of imputing missing values...
2020-08-13 10:51:04,395 : INFO : End of imputing missing values...
2020-08-13 10:51:04,395 : INFO : Start of feature encoding...
2020-08-13 10:51:04,399 : INFO : End of feature encoding...
2020-08-13 10:51:04,399 : INFO : Start of splitting features and label ...
2020-08-13 10:51:04,400 : ERROR : Exception raised while splitting features and label:"['Approved'] not found in axis"
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"
2020-08-13 10:51:04,507 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 343, in preprocess_trainset
    self.X, self.y = self.split_features_label(data, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 278, in split_features_label
    raise Exception()
Exception
2020-08-13 10:51:04,510 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 272, in split_features_label
    axis=1)  # drop the columns specified and separate the feature columns
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\frame.py", line 4117, in drop
    errors=errors,
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3914, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\generic.py", line 3946, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\indexes\base.py", line 5340, in drop
    raise KeyError("{} not found in axis".format(labels[mask]))
KeyError: "['Approved'] not found in axis"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 343, in preprocess_trainset
    self.X, self.y = self.split_features_label(data, label_name='Approved')
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 278, in split_features_label
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 348, in preprocess_trainset
    raise Exception
Exception
